### ISSUE TITLE
Universal Rendering throws "window is not defined" error

### ISSUE THREAD

**Issue by abhijeet1403** [salemdar/ngx-cookie#51]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
On following the steps mentioned in the documentation. 

In \dist\server.js:322779

!function(e,t){ true?module.exports=t(__webpack_require__(0),__webpack_require__(4)):"function"==typeof define&&define.amd?define(["@angular/core","@angular/common"],t):"object"==typeof exports?exports["ngx-cookie"]=t(require("@angular/core"),require("@angular/common")):e["ngx-cookie"]=t(e["@angular/core"],e["@angular/common"])}(window,function(e,t){return function(e){var t={};function o(r){if(t[r])return t[r].exports;var n=t[r]={i:r,l:!1,exports:{}};return e[r].call(n.exports,n,n.exports,o),n.l=!0,n.exports}return o.m=e,o.c=t,o.d=function(e,t,r){o.o(e,t)||Object.defineProperty(e,t,{configurable:!1,enumerable:!0,get:r})},o.r=function(e){Object.defineProperty(e,"__esModule",{value:!0})},o.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return o.d(t,"a",t),t},o.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},o.p="/",o(o.s=7)}([function(e,t,o){"use strict";var r=this&&this.__decorate||function(e,t,

ReferenceError: window is not defined

**Expected/desired behavior**
Should compile fine as mentioned in the docs.

**Reproduction of the problem**
Just follow the steps mentioned in the readme of this repository.

**What is the expected behavior?**
No compilation errors.

**What is the motivation / use case for changing the behavior?**
To get this library working with Universal

**Please tell us about your environment:**

* **ngx-cookie version:** ^3.0.1

* **Angular version:** ^5.2.9
 
* **Browser:** Chrome

**Comment by rshchpkn** [comment]
+1

**Comment by martinambrus** [comment]
+1

**Comment by orestisioakeimidis** [comment]
+1

**Comment by realmx** [comment]
+1

**Comment by mgol** [comment]
I've just hit it too. Works fine with `ngx-cookie@2.0.1`.

**Comment by EndyKaufman** [comment]
after downgrade to ngx-cookie@2.0.1 
new error
Cannot set property 'cookie' of undefined

**Comment by phil123456** [comment]
any fix for this ?

**Comment by stephenautomatik** [comment]
I have the same issue as @navdeepkumar

**Comment by stephenautomatik** [comment]
Just upgraded to v3.0.1 and now I have the same issue as OP

**Comment by AmebaBrain** [comment]
Had the same error as OP

- ngx-cookie  version: ^3.0.1
- Angular version: ^6.0.0
- Browser: Chrome

$ sed -n 214731,214731p dist/server.js 
!function(e,t){ true?module.exports=t(__webpack_require__(7),__webpack_require__(350)):undefined}(**window**,function(e,t)...

Fix proposed by @joscmw95  works! many thanks for pointing it out
Anyway, think it's a bug and module need to implement provider for window. For example as it done in [Window Service](http://brianflove.com/2016/10/10/angular-2-window-scroll-event-using-hostlistener/) chapter.

**Comment by stephenautomatik** [comment]
Tried the workaround above and now I have the same error as before: 

ERROR { Error: StaticInjectorError[REQUEST]: 
  StaticInjectorError(Platform: core)[REQUEST]: 
    NullInjectorError: No provider for REQUEST!
...

**Comment by joscmw95** [comment]
make sure you followed the instructions to use ngx-cookie in Angular Universal, this error is probably because you didn't provide the CookieBackendService with the 'REQUEST' object.

The instructions are [here](https://github.com/salemdar/ngx-cookie#-angular-universal-usage), add these to your server.ts:
```
/* server.ts */

// Find the call to res.render() in the file and
// update it with providers for 'REQUEST' and 'RESPONSE'

app.get('*', (req, res) => {
  res.render('index', {
    req: req,
    res: res,
    providers: [
      {
        provide: 'REQUEST', useValue: (req)
      },
      {
        provide: 'RESPONSE', useValue: (res)
      }
    ]
  });
});
```

**Comment by stephenautomatik** [comment]
I followed the instructions exactly as they're shown and have my server.ts file set up as specified, but with the Angular Universal code commented out for comparison:

```
...

app.get('*', (req, res) => {
  // res.render(join(DIST_FOLDER, 'browser', 'index.html'), { req });
  res.render('index', {
    req: req,
    res: res,
    providers: [
      {
        provide: 'REQUEST', useValue: (req)
      },
      {
        provide: 'RESPONSE', useValue: (res)
      }
    ]
  });
});
...
```

I also tried replacing 'index' in the demo code with the index.html reference from the Universal demo, but I keep getting the same error. The app works perfectly without SSR and I was able to get SSR working without ngx-cookie. However, I'd prefer to keep using this service since I have a few other services and components that rely on it, but I need SSR to work.

**Comment by joscmw95** [comment]
My apologies, I just realized that the docs in this repository's README.md is not correctly giving the proper configuration for server.ts -- at least of the latest version.

I believe your server.ts is similar to something like [this](https://github.com/angular/universal-starter/blob/master/server.ts), in that case, add these codes to the lines:

```
// Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
app.engine('html', ngExpressEngine({
  bootstrap: AppServerModuleNgFactory,
  providers: [
    provideModuleMap(LAZY_MODULE_MAP),
    {
      provide: 'REQUEST', useValue: (options.req)
    },
    {
      provide: 'RESPONSE', useValue: (options.res)
    }
  ]
}));
```

**Comment by stephenautomatik** [comment]
What do 'options.req' and 'options.res' refer to? Getting an error saying options can't be found.

And do I need to include these providers in both app.engine and the index render endpoint?

**Comment by joscmw95** [comment]
My bad, I've updated the snippet. Only on app.engine.

**Comment by stephenautomatik** [comment]
Alright I got it working. Thank you!

Now there's just the issue of having to manually update `node_modules/ngx-cookie/bundles/ngx-cookie.umd.js`

If that can be resolved I think we'll be in business.

**Comment by rossanmol** [comment]
After fixing the issue with the window, I am having same error as @EndyKaufman:
`Cannot set property 'cookie' of undefined`
