### ISSUE TITLE
ngx-cookie won't compile with Angular CLI 1.6.0

### ISSUE THREAD

**Issue by hhmultimediallc** [salemdar/ngx-cookie#42]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

Build freezes at 70% with the error

**Expected/desired behavior**

Error free compilation

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar.

**ng serve**
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 16% building modules 50/59 modules 9 active ...tion\node_modules\ngx-cookie\index.jsError: No module factory available for dependency type: ContextElementDependency
    at Compilation.addModuleDependencies (C:\git-hcm\optimizer2\Presentation\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:215:21)
    at Compilation.processModuleDependencies (C:\git-hcm\optimizer2\Presentation\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:204:8)
    at _this.buildModule.err (C:\git-hcm\optimizer2\Presentation\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:359:14)
    at building.forEach.cb (C:\git-hcm\optimizer2\Presentation\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:149:27)
    at Array.forEach (<anonymous>)
    at callback (C:\git-hcm\optimizer2\Presentation\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:149:13)
    at module.build (C:\git-hcm\optimizer2\Presentation\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:176:11)
    at resolveDependencies (C:\git-hcm\optimizer2\Presentation\node_modules\@angular\cli\node_modules\webpack\lib\ContextModule.js:165:4)
    at ContextModule.result.resolveDependencies (C:\git-hcm\optimizer2\Presentation\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:431:25)
    at ContextModule.build (C:\git-hcm\optimizer2\Presentation\node_modules\@angular\cli\node_modules\webpack\lib\ContextModule.js:105:8)
    at Compilation.buildModule (C:\git-hcm\optimizer2\Presentation\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:151:10)
    at factoryCallback (C:\git-hcm\optimizer2\Presentation\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:344:12)
    at C:\git-hcm\optimizer2\Presentation\node_modules\@angular\cli\node_modules\webpack\lib\ContextModuleFactory.js:95:13
    at C:\git-hcm\optimizer2\Presentation\node_modules\tapable\lib\Tapable.js:268:11
    at done.then (C:\git-hcm\optimizer2\Presentation\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:433:28)
    at <anonymous>                                                                   70% building modules 1809/1809 modules 0 active^CTerminate batch job (Y/N)? y

**What is the expected behavior?**

        Error free build

**What is the motivation / use case for changing the behavior?**

        N/A

**Please tell us about your environment:**

        "ngx-cookie": "^2.0.1",

        "@angular/cli": "1.6.0-rc.2",
        "@angular/compiler-cli": "5.1.0",
        "@angular/core": "5.1.0",
        "@angular/language-service": "4.4.3",

        "@angular/cdk": "5.0.0",
        "@angular/material": "5.0.0",
        "@angular/common": "5.1.0",
        "@angular/animations": "5.1.0",
        "@angular/compiler": "5.1.0",
        "@angular/forms": "5.1.0",
        "@angular/http": "5.1.0",
        "@angular/platform-browser": "5.1.0",
        "@angular/platform-browser-dynamic": "5.1.0",
        "@angular/platform-server": "5.1.0",
        "@angular/router": "5.1.0",

* **Browser:** 

        Chrome 62.0.3202.94 (Official Build) (64-bit)

* **Notes:** 

ngx-cookie builds with all versions of angular/cli 1.6.0-rc.1 and below.

**Comment by tmsoft** [comment]
I get the following compile error:
ERROR in node_modules/ngx-cookie/src/cookie-options-provider.d.ts(1,20): error TS2305: Module '"/Users/Todd/dev/tmsoft/market-admin/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

**Comment by hhmultimediallc** [comment]
Is anyone looking into this issue?

**Comment by newaeonweb** [comment]
@hhmultimediallc i have the same issue, and i can't find a solution yet.
